set(_CATKIN_CURRENT_PACKAGE "ros_robot_navigation")
set(ros_robot_navigation_VERSION "0.0.0")
set(ros_robot_navigation_MAINTAINER "kist <kist@todo.todo>")
set(ros_robot_navigation_PACKAGE_FORMAT "1")
set(ros_robot_navigation_BUILD_DEPENDS "dynamixel_sdk" "roscpp" "std_msgs" "message_generation" "dynamixel_controller_msg" "action_execution_msgs" "move_base_msgs" "geometry_msgs" "actionlib_msgs" "tf" "msgCommand2")
set(ros_robot_navigation_BUILD_EXPORT_DEPENDS "dynamixel_sdk" "roscpp" "std_msgs" "message_generation" "dynamixel_controller_msg" "action_execution_msgs" "move_base_msgs" "geometry_msgs" "actionlib_msgs" "tf" "msgCommand2")
set(ros_robot_navigation_BUILDTOOL_DEPENDS "catkin")
set(ros_robot_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(ros_robot_navigation_EXEC_DEPENDS "dynamixel_sdk" "roscpp" "std_msgs" "message_generation" "dynamixel_controller_msg" "action_execution_msgs" "move_base_msgs" "geometry_msgs" "actionlib_msgs" "tf" "msgCommand2")
set(ros_robot_navigation_RUN_DEPENDS "dynamixel_sdk" "roscpp" "std_msgs" "message_generation" "dynamixel_controller_msg" "action_execution_msgs" "move_base_msgs" "geometry_msgs" "actionlib_msgs" "tf" "msgCommand2")
set(ros_robot_navigation_TEST_DEPENDS )
set(ros_robot_navigation_DOC_DEPENDS )
set(ros_robot_navigation_DEPRECATED "")